config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks'}
  resources :product, only: [:show]
  resources :category, only: [:show]
  resource  :cart, only: %i[destroy show] do 
    resources :items, only: %i[destroy create] 
  end
  resources :search, only: [:index]
  get "/cart/items" =>  "items#create"

  root to: 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
    
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items, dependent: :destroy
    has_many :products, through: :cart_items
    belongs_to :user

    validates :user_id, presence: true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :product
    belongs_to :cart

    validates :cart_id, :quantity, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
    has_ancestry
    has_many :products
end

app/models/gallery.rb
class Gallery < ApplicationRecord
    belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    validates :title, presence: true
    validates :price, presence: true

    has_many :galleries

    belongs_to :category

    has_many :related_product
    has_many :related, through: :related_product

    enum hit: { hit: 1, not_hit: 0 }
    #scope :active, -> { where(status: 1)}
end

app/models/related_product.rb
class RelatedProduct < ApplicationRecord
    belongs_to :product
    belongs_to :related, class_name: 'Product'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable,
          :omniauthable, omniauth_providers: [:facebook]

  has_one :cart, dependent: :destroy

  validates :email,  presence: true
  validates :password,  presence: true

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    include CartsHelper


    def show; end

    def destroy
        current_cart.destroy
        render :show
    end



end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    include CartsHelper
    layout false

    def create
        cart_items.create(item_params)
    end
    
    def destroy
        cart_items.find_by(item_params).destroy
        render :create
    end

    private
    def item_params
        params.permit(:product_id, :quantity)
    end
    helper_method :products
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    before_action :set_page_options
    def index 
        @brands = Brand.limit(3)
        @hits =   Product.all.limit(8)

    end
    def set_page_options
        @page_title = "Watches Shop"
        @page_description = "Watches"
        @page_keywords = "Man Woman Kids"
    end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
    after_action :register_visit, only: [:show]
    
    def show
        @product = Product.find(params[:id])
        set_page_options
    end
    
    helper_method :recent_products
    attr_accessor :product
    
    
    def recent_products
        [] if recently.none?
        Product.where(id: recently)
    end
    def recently
        session[:viewed_products] ||= []
    end
    def register_visit
        session[:viewed_products] ||= []
        session[:viewed_products] = ([@product.id] + session[:viewed_products]) 
                                    .uniq 
                                    .take(3)
    end         
    

    def set_page_options
        set_meta_tags product.slice(:title, :keywords, :description)
        add_breadcrumb 'Home', root_path, title: 'Home'
    end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    before_action :set_page_options

    def index
        @products = text_search
    end

    def set_page_options
        set_meta_tags title: 'Search'
        add_breadcrumb 'Home', :root_path, title: 'Home'
    end

    def search_params
        params.permit(:query)   
    end

    def text_search
        search_text = [ '%',search_params[:query].strip,'%'].join
        Product.where('title ILIKE ?', search_text)
    end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper

    def products
        @products ||= cart_items.joins(:product).all
    end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/carts/show.html.erb
<%= render 'include/cart/cart'%>

app/views/include/cart/_cart.html.erb
<%  unless current_user.nil?  %>
    <% if !products.empty? %>
    <div class="table table-hover table-striped">
    <thead>
    <tr>
        <th>Photo</th>
        <th>Bytitle</th>
        <th>Count</th>
        <th>Price</th>
        <th><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></th>
    </tr>
    </thead>
    <tbody>
    <% qty = [] %>
    <% sum = [] %>
    <%= @products.map do |item| %>
    <tr>
        <td>
            <% if item.product.img.nil? %>
                <%= link_to(item.product.title, item.product) %>
            <%else%>
                <%= link_to(image_tag(item.product.img), item.product) %>
            <% end %>
        </td>
        <td><%= link_to(item.product.title, item.product) %></td>
        <td>
        <% qty << item.quantity %> <%= item.quantity %>
        </td>
        <% pr = item.quantity * item.product.price %>
        <% sum << pr %>
        <td><%= item.product.price %></td>
        <td>
            <span data-id="<%= item.product_id%>" class="glyphicon glyphicon-remove text-denger del-item" aria-hidden="true"></span></td>
    </tr>
    <% end %>
    <tr>
    <td>Total</td>
    <td colspan="4" class="text-right cart-qty"><%= qty.sum %></td>
    </tr>
    <tr>
    <td>Sum:</td>
    <td colspan="4" class="text-right cart-sum"><%= format.("%.2f", sum.sum)%>$</td>
    </tr>

    </tbody>
    </table>
    </div>
    <% else %>
    <h3>Cart is Empty</h3>

    </tbody>
    <% end %>
    <%else%>
    <span>Please sing in! To view the cart</span>
    <script>$('#cart .modal-footer a,#cart .modal-footer  .btn-danger').css('display', 'none');</script>
    <% end %>

app/views/product/show.html.erb
<div class="breadcrumbs">
<div class="container">
<div class="breadcrumbs-main">
<ol class="breadcrumbs">
    <li><a href="/"><%= render_breadcrumbs %></a></li>
    <li class="active"><%= @product.title %></li>
</ol>
</div>
</div>
</div>
<!-- start single-->
<div class="single contact">
<div class="container">
<div class="single-main">
<div class="col-md-9 single-left">
<div class="sngl-top">
<div class="col-md-5 single-top-left">




<div class="flexslider">


    <div class="thumb-image"> <%= image_tag @product.img, class: "img-responsive"%> </div>

</div>




</div>
<div class="col-md-7 single-top-right">
    <div class="single-para simpleCart_shelfItem">
        <h2> <%= @product.title %></h2>
        <div class="star-on">
            <ul class="star-footer">
                <li><a href="#"><i> </i></a></li>
                <li><a href="#"><i> </i></a></li>
                <li><a href="#"><i> </i></a></li>
                <li><a href="#"><i> </i></a></li>
                <li><a href="#"><i> </i></a></li>
            </ul>
            <div class="review">
            <a href="#"> 1 customer review</a>
            </div>
            <div class="clearfix"> </div>
            </div>

            <h5 class="item_price">$ <%= @product.price %> </h5>
            <% if @product.old_price %>
                <del><%= @product.old_price %> </del>
            <% end %>
            <p><%= @product.content %> </p>
            <div class="available">
                <ul>
                    <li>Color
                    <select>
                        <option>Silver</option>
                        <option>Black</option>
                        <option>Dark Black</option>
                        <option>Red</option>
                    </select>
                    <li>
                    <div class="clearfix"> </div>
                </ul>
                </div>
                <ul class="tag-men">
                <li><span>CATEGORY</span>
                <strong>:
                </strong>
                </li>
                </ul>
                <div class="quantity">
                    <input type="number" size="4" value="1" name="quantity" min="1" step="1">

                </div>

            <%= link_to'ADD TO CART',   cart_items_path,
                                            remote: true, 
                                            data: { method: :post, id: @product.id },
                                            class:   "add-cart item_add add-to-cart-link",
                                            id:       "productAdd"%>

                </div>
                </div>
            <div class="clearfix"> </div>
        </div>
    <div class="tabs">
        <ul class="menu_drop">
            <li class="item1"><a href="#"><img src="<%= asset_path "arrow.png" %>" alt=""> Description</a>
            
            </li>
            <li class="item2"><a href="#"><img src="<%= asset_path "arrow.png" %>" alt="">Additional Information</a>
            
            </li>
            <li class="item3"><a href="#"><img src="<%= asset_path "arrow.png" %>" alt="">Reviews</a>
        
            </li>
            
            </li>
        </ul>
    </div>
<% unless @product.related.nil? %>
    

    <div class="latestproducts">
        <div class="product-one">
            <h3>Related Product</h3>
            <% @product.related.each do |related| %>
            <div class="col-md-4 product-left p-left">
                <div class="product-main simpleCart_shelfItem">
                    <a href="<%= related.id%>" class="mask">
                        <img class="img-responsive zoom-img" src="<%= asset_path related.img %>" alt="" />
                        </a>
                    <div class="product-bottom">
                        <h3><a href="<%= related.id %>"><%= related.title %></a></h3>
                        <p>Explore Now</p>
                        <h4>
                        <a class="item_add add-to-cart-link" href="cart/add?id=<%= related.id %>" data-id="<%= related.id%>">  <i> </i>
                        </a>
                        <span class="item_price">$ <%= related.price %></span>
                        <% if related.old_price %>
                            <del><%= related.old_price %> </del>
                        <% end %>
                        </h4>
                    </div>
                <div class="srch">
                <span>-50%</span>
                </div>
            </div>
        </div>
    <% end %>
    <div class="clearfix"> </div>
    </div>
</div>
<% end %>

<% if recent_products.any? %>

    <div class="latestproducts">
        <div class="product-one">
            <h3> Recently Products</h3>

            <% recent_products.each do |recently| %>


            <div class="col-md-4 product-left p-left">
                <div class="product-main simpleCart_shelfItem">
                    <a href="<%= recently.id%>" class="mask">
                        <img class="img-responsive zoom-img" src="<%= asset_path recently.img %>" alt="" />
                    </a>
                    <div class="product-bottom">
                        <h3><a href="<%= recently.id %>"><%= recently.title %></a></h3>
                        <p>Explore Now</p>
                        <h4>
                        <a class="item_add add-to-cart-link" href="cart/add?id=<%= recently.id %>" data-id="<%= recently.id%>">  <i> </i>
                        </a>
                        <span class="item_price">$ <%= recently.price %></span>
                        <% if recently.old_price %>
                            <del><%= recently.old_price %> </del>
                        <% end %>
                        </h4>
                    </div>
                <div class="srch">
                <span>-50%</span>
                </div>
            </div>
        </div>
    <% end %>
    <div class="clearfix"> </div>
    </div>
</div>
<% end %>
</div>

<div class="col-md-3 single-rigth">
    <div class="w_sidebar">
    <section class="sky-form">
            <h4>Categories</h4>
            <div class="col col-4">
                <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i></i>All Accessories</label>
                </div>
                <div class="col col-4">
                <label class="checkbox"><input type="checkbox" name="checkbox" ><i></i>Women Watches</label>
                <label class="checkbox"><input type="checkbox" name="checkbox" ><i></i>Kids Watches</label>
                <label class="checkbox"><input type="checkbox" name="checkbox" ><i></i>Men Watches</label>
                </div>
            </div>
        </section>
    
        <section class="sky-form">
            <h4>Brand</h4>
            <div class="row1 row2 scroll-pane">
            <div class="col col-4">
            <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i> </i>Kurtas</label>
                </div>
                <div class="col col-4">
                <label class="checkbox"><input type="checkbox" name="checkbox" ><i> </i>Sonata</label>
                <label class="checkbox"><input type="checkbox" name="checkbox" ><i> </i>Titan</label>
                <label class="checkbox"><input type="checkbox" name="checkbox" ><i> </i>Casio</label>
                <label class="checkbox"><input type="checkbox" name="checkbox" ><i> </i>Omax</label>
                <label class="checkbox"><input type="checkbox" name="checkbox" ><i> </i>Shree</label>
                <label class="checkbox"><input type="checkbox" name="checkbox" ><i> </i>Fastrack</label>
                <label class="checkbox"><input type="checkbox" name="checkbox" ><i> </i>Sports</label>
                <label class="checkbox"><input type="checkbox" name="checkbox" ><i> </i>Fossil</label>
                <label class="checkbox"><input type="checkbox" name="checkbox" ><i> </i>Maxima</label>
                <label class="checkbox"><input type="checkbox" name="checkbox" ><i> </i>Diesel</label>
                </div>
            </div>
        </section>
        <section class="sky-form">
            <h4>Colour</h4>
            <ul class="w_nav2">
                <li><a class="color1" href="#"></a></li>
                <li><a class="color2" href="#"></a></li>
                <li><a class="color3" href="#"></a></li>
                <li><a class="color4" href="#"></a></li>
                <li><a class="color5" href="#"></a></li>
                <li><a class="color6" href="#"></a></li>
                <li><a class="color7" href="#"></a></li>
                <li><a class="color8" href="#"></a></li>
                <li><a class="color9" href="#"></a></li>
                <li><a class="color10" href="#"></a></li>
            </ul>
        </section>
        <section class="sky-form">
            <h4>Discount</h4>
            <div class="row1 row2 scroll-pane">
            <div class="col col-4">
                <label class="radio"><input type="radio" name="radio"checked="" ><i> </i>60 % and above</label>
                <label class="radio"><input type="radio" name="radio" ><i> </i>50 % and above</label>
                <label class="radio"><input type="radio" name="radio" ><i> </i>40 % and above</label>
                </div>
                <div class="col col-4">
                <label class="radio"><input type="radio" name="radio" ><i> </i>30 % and above</label>
                <label class="radio"><input type="radio" name="radio" ><i> </i>20 % and above</label>
                <label class="radio"><input type="radio" name="radio" ><i> </i>10 % and above</label>
                </div>
            </div>
        </section>
        </div>
        </div>
    <div class="clearfix"> </div>
    </div>
    </div>
</div>
<input type="hidden" value="<%= !current_user.nil? ? 88 : 99 %>" id="cart_access" /> 

<!--- end --->



            



                